apiVersion: v1
kind: Service
metadata:
  name: k8s-service
  namespace: app4
spec:
  selector:
    app: k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
